
import React from 'react';

const PROTOCOLS = [
  { id: 'SOP-01', title: 'Data Integrity', desc: 'All incoming visual matrices must be scanned for structural inconsistencies before heuristic analysis.' },
  { id: 'SOP-02', title: 'Asset Isolation', desc: 'Monochromatic extraction is mandatory for clear-channel artifact identification.' },
  { id: 'SOP-03', title: 'Neural Synthesis', desc: 'Synthesized assets are session-specific and subject to the Nano Banana Pro security policy.' },
  { id: 'SOP-04', title: 'Forensic Reporting', desc: 'Linguistic reports generated by the Inspector module are to be treated as high-probability inferences.' }
];

const ProtocolModal: React.FC<{ isOpen: boolean; onClose: () => void }> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-6 bg-black/90 backdrop-blur-md animate-in fade-in duration-500">
      <div className="max-w-2xl w-full border border-white/20 bg-black p-12 space-y-12 relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-[1px] bg-white/20 animate-pulse"></div>
        
        <div className="flex justify-between items-start">
          <div className="space-y-2">
            <h2 className="font-serif text-4xl uppercase tracking-tighter">System Protocols</h2>
            <p className="font-mono text-[9px] tracking-[0.5em] opacity-30 uppercase italic">Digital Forensics Operations Manual</p>
          </div>
          <button onClick={onClose} className="font-mono text-xs opacity-40 hover:opacity-100 tracking-widest">[CLOSE_EXIT]</button>
        </div>

        <div className="grid gap-8">
          {PROTOCOLS.map(p => (
            <div key={p.id} className="space-y-2 group">
              <div className="flex items-center gap-4">
                <span className="font-mono text-[8px] opacity-20 border border-white/10 px-2 py-0.5">{p.id}</span>
                <h4 className="font-mono text-[11px] tracking-widest font-bold uppercase">{p.title}</h4>
              </div>
              <p className="font-mono text-[10px] opacity-40 leading-relaxed uppercase pl-16 group-hover:opacity-60 transition-opacity">
                {p.desc}
              </p>
            </div>
          ))}
        </div>

        <div className="pt-8 border-t border-white/5 flex justify-between items-center opacity-20 font-mono text-[7px] tracking-[0.4em] uppercase">
          <span>Auth: Investigator_L4</span>
          <span>Clearance: Restricted</span>
        </div>
      </div>
    </div>
  );
};

export default ProtocolModal;
